config/routes.rb
IdeaSource::Application.routes.draw do
  resources :tags

  resources :idea_nodes

  devise_for :users, :path_names => { :sign_up => "register"}
<<<<<<< HEAD
  devise_for :users, :sign_out_via => [ :delete]
=======
  devise_for :users, :sign_out_via => [ :delete,:get ]
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
  
	root :to => "home#index"
	match 'mindmap/:id' => 'mindmap#map', :as => :map
	match 'discover' => 'mindmap#discover', :as => :discover
  match 'discover/:search_value' => 'mindmap#discover'
	match 'search/:tag/:sort_by' => 'mindmap#search', :as => :search
  match 'search/:tag/:sort_by/:search_value' => 'mindmap#search'
	match 'user/:username' => 'home#userhome', :as => :user
  
	match 'about' => 'home#about', :as => :about
	match 'homepage' => "home#index"
	match 'idea_nodes/new/:rootId/:parentId' => 'idea_nodes#new'
<<<<<<< HEAD
	
	
=======
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  protect_from_forgery
<<<<<<< HEAD
  layout "application"
=======
  layout "home"
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
  
  def userhome
  	@ideas = IdeaNode.where(:username => params[:username], :parentId => 0)
  	@ideacount = @ideas.count
<<<<<<< HEAD
  end 	
=======
  end 
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
end

app/helpers/home_helper.rb
module HomeHelper
	def resource_name
  		:user
  	end

  	def resource
  		@resource ||= User.new
  	end

  	def devise_mapping
  		@devise_mapping ||= Devise.mappings[:user]
  	end
end

app/views/home/about.html.erb
<<<<<<< HEAD
  	<% content_for :style do %>
    <%= stylesheet_link_tag "about"%>
    <% end %>
    <input id="pageName" type="hidden" value="about">
  	<div id="content">
    <a href="homepage"><img id="logo" src="<%= asset_path 'logot2f1.png' %>" alt="IdeaSource Logo"/></a>
  	<div id="humans" class="text">
  	<img id="pic" src="<%= asset_path 'DiscoverSmall.png' %>" alt="IdeaSource Logo"/>
    <br>
  	<p>IdeaSource was developed in 2013 at the University of Waikato, for a 3rd year University Assignment by Daniel Manning and Haley Littlewood</p>
    <p>IdeaSource is a place where people can come when they need an idea for something or they have ideas about things but dont know what to do with them.</p>
  	</div>
  	<div id="howto" class="text">
  	<h3>Overview:</h3>
  	<p>People have ideas but don't know what to do with them, also people need ideas but cant think of any.
The solution is to get these people together so they can share and contribute to ideas.</p><br/>
<section id="images">
  	<figure tabindex="1">
  		<img id="pic" src="<%= asset_path 'homescreen.png' %>" alt="IdeaSource homescreen" contenteditable="false"/>
  		<figcaption contenteditable="false">Home page</figcaption>
  	</figure>
  	<figure tabindex="2">
  		<img id="pic" src="<%= asset_path 'mindmapTHUMB.png' %>" alt="IdeaSource Mindmap" contenteditable="false"/>
  		<figcaption contenteditable="false">Mindmap</figcaption>
  	</figure>
  	<figure tabindex="3">
  		<img id="pic" src="<%= asset_path 'search.png' %>" alt="IdeaSource Search" contenteditable="false"/>
  		<figcaption contenteditable="false">Search function</figcaption>
  	</figure>
</section>
<h3>Target Audience:</h3>
<p>Students, Companies, Philanthropists and the general public.</p>
<h4>Audience Scale: </h4>
<p> Global, starting small 10-100per day, growing to thousands of users per day.</p>

<h3>Main Feature:</h3>
<p>A searchable Mindmap of ideas, created and extended by users.</p>
  	

<br/>
  	
  		<video controls>
          <source src="<%= asset_path 'videoMINDMAP.mp4' %>" type="video/mp4">
          Your Browser is archaic. Please try updating or using a more modern browser
      </video>
<br/>
<p>This product is the only thing like it in existence. It combines crowd sourcing ideas with an intuitive user interface, meaning it is appealing and has a point of difference from generic forums. </p>

  	</div>
</div>
=======
  	<header>
  		<a href="homepage"><img id="logo" src="<%= asset_path 'logot2f1.png' %>" alt="IdeaSource Logo"/></a>
  	</header>
  	<div id="profileBar">
  	</div>
  	<div id="content">
  	<p>IdeaSource was developed in 2013 at the University of Waikato, for a 3rd year University Assignment by Daniel Manning and Haley Littlewood</p>
    <p>IdeaSource is a place where people can come when they need an idea for something or they have ideas about things but dont know what to do with them.</p>
  	</div>
  	<footer>
  		<p> All rights reserved.</p>
  	</footer>
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

app/views/home/index.html.erb
<<<<<<< HEAD
<input id="pageName" type="hidden" value="home">
        <div class="container">
            
            <div class="hero-unit">
                <img id="logo" src="<%= asset_path 'logot2f1.png' %>" alt="IdeaSource Logo"/>
                <p>IdeaSource is a web application that allows users to share and find ideas </p>
            </div>

            <div class="row">
                <div class="span4">
                </div>
                <div class="span4">
                    <img src="<%= asset_path 'mindmap.png' %>" alt="A Mindmap">
               </div>
                <div class="span4">
                </div>
            </div>

           
        </div> <!-- /container -->
=======
<!DOCTYPE html>
<html>
<head>	
  <title>IdeaSource</title>
  	<% content_for :style do %>
  	<%= stylesheet_link_tag "main" %>
  	<%= stylesheet_link_tag "userHome" %>
  	<% end %>
  	<link rel="stylesheet" type="text/css" href="colours.css"/>
</head>
<body>
	<div id="profileBar">
		<% if user_signed_in? %>
  		<div class="userbutton"><%= link_to "User  Home", user_path(:username => current_user.username)	%></div>
  		<%else %>
  		<div class="userbutton">
  		<%= link_to "Sign in", new_user_session_path %> 
  		</div> 
  		<div class="userbutton"> <%= link_to "Sign up", new_user_registration_path %>
  		</div>
  		<% end %>
  	</div>
	<header>
		
  			<img id="logo" src="<%= asset_path 'logot2f1.png' %>" alt="IdeaSource Logo"/>
  		
  	</header>
  	<div id="content">
  		<section>
  			<img alt="Ideasource MindMap" src="<%= asset_path 'mindmap.png' %>"/>
  		</section>
  		<aside>
  			<p> IdeaSource is a web application that allows users to share and find ideas </p>
  		</aside>
  	</div>
  	<footer>
  		<p> All rights reserved. <%= link_to "About IdeaSource", about_path %> </p>
  	</footer>
</body>
</html>
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

app/views/home/splash.html.erb
<!DOCTYPE html>
<html>
  <head>
	<link rel="stylesheet" type="text/css" href="userhome.css"/>
  	<title>IdeaSource</title>
  </head>
  <body>
  	<header>
  		<a href="homepage">LOGO HERE</a>
  	</header>
  	<div id="profileBar">
  	<%if user_signed_in? %>
		Hi there <%= current_user.username %>! Not you?
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete  %> 
  	</div>
  	<div id="content">
  		<section>
  			<div class="modules" id="userDetails">
  				<h3>About <%= current_user.username %></h3>
  				<table>
  					<tr>
  						<td>Ideas: 
  						<% if @ideacount.nil? ||@ideacount > 0 %>
  							0
  						<%else %>
  							<%= @ideacount %>
  						<% end %></td>
  						<td><%= %></td>
  						</tr><tr>
  						<td>Last Online: </td>
  						<td><%= current_user.last_sign_in_at%></td>
  						</tr><tr>
  						<td>Number of Sign-ins: </td>
  						<td><%= current_user.sign_in_count%></td>
  					</tr>
  				</table>
  				<%if user_signed_in? %>
  					<%= link_to "Change Password", edit_user_registration_path %>
  				<% end %>
  			</div>
  			<div id="lists" class="modules">
  				<h3>My Ideas:</h3>
  				<ul>
  				<% if @ideacount.nil? ||@ideacount > 0 %>
  					You haven't added any ideas yet.  
  				<% else %>		
  					<%= @ideas.each do |node| %>
   					<li><a href="/mindmap/<%= node.id %>">node.title</a></li>
  				<% end %>
  				</ul>
  			</div>
  		</section>
  		<aside>
  			<div id="score" class="modules">
  				<h3> <%= current_user.username %>'s Points:</h3>
  				<h1>
  					<% if current_user.userpoints.nil? %>
  						0
  					<% else %>
  						<%= current_user.userpoints %>
  					<% end %>
  				</h1>
  			</div>
  			<div id="notifications" class="modules">
  				<h3> Notifications: </h3>
  				<ul>
  					<li>Ideasource just reached 100 users, yipee!</li>
  					<li><a href="discover">Discover</a> more ideas!</li>
  					<li>IdeaSource is brought to you by toast and many other breakfast nums</li>
  				</ul>
  			</div>
  		</aside>
  		<% else %>
  		Sorry, you must be logged in to view this page.
  		<br/>
		<%= link_to "Sign in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %>
		</div>
		<% end %>
  	</div>
  	<footer>
  		<p> All rights reserved. <a href="about.html">About Ideasource</a> </p>
  	</footer>
  </body>
</html>

app/views/home/userhome.html.erb
<<<<<<< HEAD
  	<% if !user_signed_in? %>
    <% content_for :script do %>
		<script type="text/javascript">
		 	 window.location.href = "new_user_session_path";
		 </script>
     <% end %>
	<% end %>
	<% content_for :style do %>
		<%= stylesheet_link_tag "userHome" %>
    <%= stylesheet_link_tag "colours"%>
  	<% end %>
  	<input id="pageName" type="hidden" value="userHome">
  	<div id="content">
      <img id="logo" src="<%= asset_path 'logot2f1.png' %>" alt="IdeaSource Logo"/>
      <div class="row">
                <div id="left" class="span4">
                    <div class="modules" id="userDetails">
                      <h3>About <%= current_user.username %></h3>
                      <table>
                        <tr>
                          <td>Ideas: </td><td>
                          <% if @ideacount.nil? ||@ideacount == 0 %>
                            0
                          <% else %>
                            <%= @ideacount %>
                          <% end %></td>
                          <td><%= %></td>
                          </tr><tr>
                          <td>Last Online: </td>
                          <td><%= current_user.last_sign_in_at%></td>
                          </tr><tr>
                          <td>Number of Sign-ins: </td>
                          <td><%= current_user.sign_in_count%></td>
                        </tr>
                      </table>
                      <%if user_signed_in? %>
                        <%= link_to "Change Password", edit_user_registration_path %>
                      <% end %>
                    </div>

                      <div id="lists" class="modules">
                      <h3>My Ideas:</h3>
                      
                      
                      <% if @ideacount.nil? ||@ideacount == 0 %>
                        You haven't added any ideas yet.  
                        <br/>
                        <a href="/idea_nodes/new/0/0"> Add a new idea</a>
                      <% else %>
                        <a href="/idea_nodes/new/0/0"> Add a new idea</a>
                        <br/>
                        <br/>
                        <ul>
                        <% @ideas.each do |node| %>
                        <li><a href="/mindmap/<%= node.id %>"><%= node.title %></a></li>
                      <% end %>
                      <% end %>
                      </ul>
                    </div>

                </div>
                <div id="right" class="span4">
                    <div id="score" class="modules">
                    <h3> <%= current_user.username %>'s Points:</h3>
                    <h1>
                      <% if current_user.userpoints.nil? %>
                        0
                      <% else %>
                        <%= current_user.userpoints %>
                      <% end %>
                    </h1>
                  </div>
                  <div id="notifications" class="modules">
                    <h3> Notifications: </h3>
                    <ul>
                      <li>Ideasource just reached 100 users, yipee!</li>
                      <li><%= link_to "Discover", discover_path %> more ideas!</li>
                      <li>IdeaSource is brought to you by toast and many other breakfast nums</li>
                    </ul>
                  </div>
               </div>
            </div>
  		</div>
  	
=======
<!DOCTYPE html>
<html>
  <head>
  	<% if !user_signed_in? %>
		<script type="text/javascript">
		 	 window.location.href = "new_user_session_path";
		 </script>
	<% end %>
	<title>IdeaSource</title>
	<% content_for :style do %>
		<%= stylesheet_link_tag "userHome" %>
  	<% end %>
  </head>
  <body>
  <div id="profileBar">
  	<%if user_signed_in? %>
		Hi there <%= current_user.username %>! <br/> Not you?
		<div class="userbutton">
			<%= link_to 'Sign out', destroy_user_session_path, :method => :delete  %>
		</div>
		<!--<a rel="nofollow" data-method="delete" href="/users/sign_out">Sign out</a> -->
		<% end %>
	</div>
  	<header>
  		<a href="homepage"><img id="logo" src="<%= asset_path 'logot2f1.png' %>"/></a>
  	</header>
  	
  	<div id="content">
  		<section>
  			<div class="modules" id="userDetails">
  				<h3>About <%= current_user.username %></h3>
  				<table>
  					<tr>
  						<td>Ideas: </td><td>
  						<% if @ideacount.nil? ||@ideacount == 0 %>
  							0
  						<% else %>
  							<%= @ideacount %>
  						<% end %></td>
  						<td><%= %></td>
  						</tr><tr>
  						<td>Last Online: </td>
  						<td><%= current_user.last_sign_in_at%></td>
  						</tr><tr>
  						<td>Number of Sign-ins: </td>
  						<td><%= current_user.sign_in_count%></td>
  					</tr>
  				</table>
  				<%if user_signed_in? %>
  					<%= link_to "Change Password", edit_user_registration_path %>
  				<% end %>
  			</div>
  			<div id="lists" class="modules">
  				<h3>My Ideas:</h3>
  				
  				
  				<% if @ideacount.nil? ||@ideacount == 0 %>
  					You haven't added any ideas yet.  
  					<br/>
  					<a href="/idea_nodes/new/0/0"> Add a new idea yo</a>
  				<% else %>
  					<a href="/idea_nodes/new/0/0"> Add a new idea yo</a>
  					<br/>
  					<br/>
  					<ul>
  					<% @ideas.each do |node| %>
   					<li><a href="/mindmap/<%= node.id %>"><%= node.title %></a></li>
  				<% end %>
          <% end %>
  				</ul>
  			</div>
  		</section>
  		<aside>
  			<div id="score" class="modules">
  				<h3> <%= current_user.username %>'s Points:</h3>
  				<h1>
  					<% if current_user.userpoints.nil? %>
  						0
  					<% else %>
  						<%= current_user.userpoints %>
  					<% end %>
  				</h1>
  			</div>
  			<div id="notifications" class="modules">
  				<h3> Notifications: </h3>
  				<ul>
  					<li>Ideasource just reached 100 users, yipee!</li>
  					<li><%= link_to "Discover", discover_path %> more ideas!</li>
  					<li>IdeaSource is brought to you by toast and many other breakfast nums</li>
  				</ul>
  			</div>
  		</aside>
  		</div>
  	<footer>
  		<p> A+ Team 2013. All rights reserved. <br/><%= link_to "About IdeaSource", about_path %> </p>
  	</footer>
  </body>
</html>
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882