config/routes.rb
IdeaSource::Application.routes.draw do
  resources :tags

  resources :idea_nodes

  devise_for :users, :path_names => { :sign_up => "register"}
<<<<<<< HEAD
  devise_for :users, :sign_out_via => [ :delete]
=======
  devise_for :users, :sign_out_via => [ :delete,:get ]
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
  
	root :to => "home#index"
	match 'mindmap/:id' => 'mindmap#map', :as => :map
	match 'discover' => 'mindmap#discover', :as => :discover
  match 'discover/:search_value' => 'mindmap#discover'
	match 'search/:tag/:sort_by' => 'mindmap#search', :as => :search
  match 'search/:tag/:sort_by/:search_value' => 'mindmap#search'
	match 'user/:username' => 'home#userhome', :as => :user
  
	match 'about' => 'home#about', :as => :about
	match 'homepage' => "home#index"
	match 'idea_nodes/new/:rootId/:parentId' => 'idea_nodes#new'
<<<<<<< HEAD
	
	
=======
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.xml
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @tags }
      format.json { render :json => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @tag }
      format.json { render :json => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @tag }
      format.json { render :json => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, :notice => 'Tag was successfully created.' }
        format.xml { render :xml => @tag, :status => :created, :location => @tag }
        format.json { render :json => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @tag.errors, :status => :unprocessable_entity }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, :notice => 'Tag was successfully updated.' }
        format.xml { head :no_content }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
        format.xml { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
      format.xml  { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>