config/routes.rb
IdeaSource::Application.routes.draw do
  resources :tags

  resources :idea_nodes

  devise_for :users, :path_names => { :sign_up => "register"}
<<<<<<< HEAD
  devise_for :users, :sign_out_via => [ :delete]
=======
  devise_for :users, :sign_out_via => [ :delete,:get ]
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
  
	root :to => "home#index"
	match 'mindmap/:id' => 'mindmap#map', :as => :map
	match 'discover' => 'mindmap#discover', :as => :discover
  match 'discover/:search_value' => 'mindmap#discover'
	match 'search/:tag/:sort_by' => 'mindmap#search', :as => :search
  match 'search/:tag/:sort_by/:search_value' => 'mindmap#search'
	match 'user/:username' => 'home#userhome', :as => :user
  
	match 'about' => 'home#about', :as => :about
	match 'homepage' => "home#index"
	match 'idea_nodes/new/:rootId/:parentId' => 'idea_nodes#new'
<<<<<<< HEAD
	
	
=======
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

end

app/models/idea_node.rb
class IdeaNode < ActiveRecord::Base
<<<<<<< HEAD
  attr_accessible :created_at, :updated_at, :description, :rating, :rootId, :parentId, :tag, :title, :username, :latitude, :longitude
=======
  attr_accessible :created_at, :updated_at, :description, :rating, :rootId, :parentId, :tag, :title, :username
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
end

app/controllers/idea_nodes_controller.rb
class IdeaNodesController < ApplicationController
  include IdeaNodesHelper
<<<<<<< HEAD
  layout "application"
=======
  layout "mindmap"
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
  # GET /idea_nodes
  # GET /idea_nodes.xml
  # GET /idea_nodes.json
  def index
    @idea_nodes = IdeaNode.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @idea_nodes }
      format.json { render :json => @idea_nodes }
    end
  end

  # GET /idea_nodes/1
  # GET /idea_nodes/1.xml
  # GET /idea_nodes/1.json
  def show
    @idea_node = IdeaNode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @idea_node }
      format.json { render :json => @idea_node }
    end
  end

  # GET /idea_nodes/new
  # GET /idea_nodes/new.xml
  # GET /idea_nodes/new.json
  def new
    @idea_node = IdeaNode.new
    @root = params[:rootId]
    @parent = params[:parentId]

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @idea_node }
      format.json { render :json => @idea_node }
    end
  end

  # GET /idea_nodes/1/edit
  def edit
    @idea_node = IdeaNode.find(params[:id])
  end

  # POST /idea_nodes
  # POST /idea_nodes.xml
  # POST /idea_nodes.json
  def create
    @idea_node = IdeaNode.new(params[:idea_node])
    check  = Tag.count(:conditions => {:name => @idea_node.tag})
    if check == 0
      Tag.create(:name => @idea_node.tag)
    end
    #desides where to go
    id = @idea_node.rootId

    respond_to do |format|

      if validateIdea(@idea_node)
      if @idea_node.save
        if id == 0
          id = @idea_node.id
        end
        format.html { redirect_to :controller => "mindmap", :action => "map",:id => id }
        format.xml { render :xml => @idea_node, :status => :created, :location => @idea_node }
        format.json { render :json => @idea_node, :status => :created, :location => @idea_node }
      else
        format.html { render :action => "new" }
        format.json { render :json => @idea_node.errors, :status => :unprocessable_entity }
        format.xml { render :xml => @idea_node.errors, :status => :unprocessable_entity }
      end
    else
        format.html { render :action => "new", :rootId => @idea_node.rootId, :parentId => @idea_node.parentId }
        format.json { render :json => @idea_node.errors, :status => :unprocessable_entity }
        format.xml { render :xml => @idea_node.errors, :status => :unprocessable_entity }
    end
    end
  end

  # PUT /idea_nodes/1
  # PUT /idea_nodes/1.xml
  # PUT /idea_nodes/1.json
  def update
    @idea_node = IdeaNode.find(params[:id])

    respond_to do |format|
      if @idea_node.update_attributes(params[:idea_node])
        format.html { redirect_to @idea_node, :notice => 'Idea node was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @idea_node.errors, :status => :unprocessable_entity }
        format.xml { render :xml => @idea_node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /idea_nodes/1
  # DELETE /idea_nodes/1.xml
  # DELETE /idea_nodes/1.json
  def destroy
    @idea_node = IdeaNode.find(params[:id])
    count = IdeaNode.where(:tag => @idea_node.tag).count
    if count == 1
      Tags.where(:name => @idea_node.tag).destroy
    end
    @idea_node.destroy

    respond_to do |format|
      format.html { redirect_to idea_nodes_url }
      format.json { head :no_content }
      format.json { head :no_content }
    end
  end
end

app/helpers/idea_nodes_helper.rb
module IdeaNodesHelper
	def validateIdea(idea)
		if idea.title == ""
			return false
		end
		if idea.description == ""
			return false
		end
		if idea.tag == ""
			return false;
		end
		return true
	end
end

app/views/idea_nodes/_form.html.erb
<%= form_for(@idea_node) do |f| %>
  <% if @idea_node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea_node.errors.count, "error") %> prohibited this idea_node from being saved:</h2>

      <ul>
      <% @idea_node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.hidden_field :rootId, :value => @root %>
  </div>
  <div class="field">
<<<<<<< HEAD
    <%= f.hidden_field :latitude %>
  </div>
  <div class="field">
    <%= f.hidden_field :longitude %>
  </div>
  <div class="field">
=======
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
    <%= f.hidden_field :parentId, :value => @parent %>
  </div>
  <div class="field">
    <%= f.hidden_field :rating, :value => 1%>
  </div>
  <div class="field">
    <%= f.hidden_field :username, :value => current_user.username %>
  </div>
  <div class="field">
<<<<<<< HEAD
    <%= f.text_field :title, :placeholder => "Title" %>
  </div>
  <div class="field">
    <%= f.text_area :description, :placeholder => "Description" %>
  </div>
  <div class="field">
    <%= f.text_field :tag, :placeholder => "Tag" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit :value => "Create Idea", :class => "btn" %>
  </div>
<% end %>

=======
    <%= f.label :title, :class => "text" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, :class => "text" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tag, :class => "text" %><br />
    <%= f.text_field :tag %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

app/views/idea_nodes/edit.html.erb
<h1>Editing idea_node</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea_node %> |
<%= link_to 'Back', idea_nodes_path %>

app/views/idea_nodes/index.html.erb
<h1>Listing idea_nodes</h1>

<table>
  <tr>
    <th>Rootid</th>
    <th>parentid</th>
    <th>Title</th>
    <th>Description</th>
    <th>username</th>
    <th>Datecreated</th>
    <th>Datemodified</th>
    <th>Rating</th>
    <th>Tag</th>
    <th></th>
    <th></th>
  </tr>

<% @idea_nodes.each do |idea_node| %>
  <tr>
    <td><%= idea_node.rootId %></td>
    <td><%= idea_node.parentId %></td>
    <td><%= idea_node.title %></td>
    <td><%= idea_node.description %></td>
    <td><%= idea_node.username %></td>
    <td><%= idea_node.created_at %></td>
    <td><%= idea_node.updated_at %></td>
    <td><%= idea_node.rating %></td>
    <td><%= idea_node.tag %></td>
    <td><%= link_to 'Show', idea_node %></td>
    <td><%= link_to 'Edit', edit_idea_node_path(idea_node) %></td>
    <td><%= link_to 'Destroy', idea_node, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea node', new_idea_node_path %>

app/views/idea_nodes/new.html.erb
<<<<<<< HEAD

<% content_for :style do %>
  <%= stylesheet_link_tag "form"%>
<% end %>
<% content_for :script do%>
	
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script>
		if (navigator.geolocation) {
		  navigator.geolocation.getCurrentPosition(success,error);
		} else {
		  error('not supported');
		}
		function success(position){
			$('#idea_node_latitude').val(position.coords.latitude);
			$('#idea_node_longitude').val(position.coords.longitude);
		}
		function error(){
			$('#idea_node_latitude').val(0);
			$('#idea_node_longitude').val(0);
		}
		
	</script>
<% end %>
=======
<% content_for :style do %>
  <%= stylesheet_link_tag "newIdea"%>
<% end %>
<% content_for :script do%>
	<%= javascript_include_tag "newIdea"%>
<% end %>
<header>New Idea</header>
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
<div id="content">
	<%= render 'form' %>
</div>

app/views/idea_nodes/show.html.erb
<p>
  <b>Rootid:</b>
  <%= @idea_node.rootId %>
</p>

<p>
  <b>Userid:</b>
  <%= @idea_node.userId %>
</p>

<p>
  <b>Title:</b>
  <%= @idea_node.title %>
</p>

<p>
  <b>Description:</b>
  <%= @idea_node.description %>
</p>

<p>
  <b>Datecreated:</b>
  <%= @idea_node.dateCreated %>
</p>

<p>
  <b>Datemodified:</b>
  <%= @idea_node.dateModified %>
</p>

<p>
  <b>Rating:</b>
  <%= @idea_node.rating %>
</p>

<p>
  <b>Tags:</b>
  <%= @idea_node.tags %>
</p>


<%= link_to 'Edit', edit_idea_node_path(@idea_node) %> |
<%= link_to 'Back', idea_nodes_path %>