config/routes.rb
IdeaSource::Application.routes.draw do
  resources :tags

  resources :idea_nodes

  devise_for :users, :path_names => { :sign_up => "register"}
<<<<<<< HEAD
  devise_for :users, :sign_out_via => [ :delete]
=======
  devise_for :users, :sign_out_via => [ :delete,:get ]
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
  
	root :to => "home#index"
	match 'mindmap/:id' => 'mindmap#map', :as => :map
	match 'discover' => 'mindmap#discover', :as => :discover
  match 'discover/:search_value' => 'mindmap#discover'
	match 'search/:tag/:sort_by' => 'mindmap#search', :as => :search
  match 'search/:tag/:sort_by/:search_value' => 'mindmap#search'
	match 'user/:username' => 'home#userhome', :as => :user
  
	match 'about' => 'home#about', :as => :about
	match 'homepage' => "home#index"
	match 'idea_nodes/new/:rootId/:parentId' => 'idea_nodes#new'
<<<<<<< HEAD
	
	
=======
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

end

app/controllers/mindmap_controller.rb
class MindmapController < ActionController::Base
  protect_from_forgery
<<<<<<< HEAD
  layout "application"
=======
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
  before_filter :authenticate_user! 
  
  def map
  	@idea_node = IdeaNode.all
  	@root = IdeaNode.find(params[:id])
  end
  def discover
    if params[:search_value] != nil
      @tags = Tag.where('name LIKE ?','%'+params[:search_value]+'%')
    elsif params[:search_value] == ""
      @tags = Tag.all
    else
      @tags = Tag.all
    end
  end

  def search
    @tag = params[:tag]
    if params[:sort_by] == "None"
      order_value = ""
    elsif params[:sort_by] == "Newest"
      order_value = "created_at desc"
    elsif params[:sort_by] == "Oldest"
      order_value = "created_at asc"
    elsif params[:sort_by] == "User"
      order_value = "username"
    elsif params[:sort_by] == "Rating"
      order_value = "rating desc"
    end
    if params[:search_value] != nil
      @ideas = IdeaNode.where("rootId = 0 AND tag = '"+params[:tag]+"' AND title LIKE ?","%"+params[:search_value]+"%").order(order_value)
    elsif params[:search_value] == ""
      @ideas = IdeaNode.where(:tag => params[:tag],:rootId => 0).order(order_value)
    else
      @ideas = IdeaNode.where(:tag => params[:tag],:rootId => 0).order(order_value)
    end
  end
end

app/helpers/mindmap_helper.rb
module MindmapHelper

	def getNodes(rootId)
		root = IdeaNode.find(rootId)
		list = content_tag(:ul) do
			content_tag(:li) do
				tmp = content_tag(:a, root.title, :id => root.id)
				IdeaNode.all.each do |node|
					if node.parentId == root.id
						tmp = tmp + getNodes(node.id)
					end 
				end
				tmp
			end
		end.html_safe
		return list
	end
end

app/views/mindmap/discover.html.erb
<% content_for :style do %>
  <%= stylesheet_link_tag "discover" %>
<% end %>
<% content_for :script do%>
	<%= javascript_include_tag "discover" %>
<% end %>
<<<<<<< HEAD
			<div id="search">
				<input id="searchBar" type="text">
				<div onclick="return search();" id="searchButton" class="btn text">Search</div>
			</div>
			<input id="pageName" type="hidden" value="discover">
=======
		<header>Discover</header>
			<div id="search">
				<input id="searchBar" type="text"><div onclick="return search();" id="searchButton" class="dark">Search</div>
			</div>
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
		<div id="content">
			<% @tags.each do |tag| %>
				<div id="<%= tag.name %>" class="tag"><%= link_to tag.name,search_path(:tag => tag.name,:sort_by => "none") %></div>
			<% end %>
		</div>

app/views/mindmap/map.html.erb
<% content_for :style do %>
  <%= stylesheet_link_tag "js-mindmap"%>
  <%= stylesheet_link_tag "mindmap" %>
<% end %>
<% content_for :script do%>
<<<<<<< HEAD
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/jquery-ui.min.js"></script>
  <%= javascript_include_tag "mindmap"%>
  <%= javascript_include_tag "raphael-min"%>
  <%= javascript_include_tag "js-mindmap"%>
<% end %>

    <div id="popup">
      <h2 id="title" class="text"></h2>
        <div class="wrapper">
          <label class="subTitle">Description: </label>
          <label id="desc" class="text"></label>
        </div>
        <div class="wrapper">
          <label class="subTitle">Author: </label>
          <label id="username" class="text"></label>
        </div>
        <div class="wrapper">
          <label class="subTitle">Created At: </label>
          <label id="created_at" class="text"></label>
        </div>
        <div class="wrapper">
          <label class="subTitle">Rating: </label>
          <label id="rating" class="text"></label>
          <img id="thumb_up" class="icon" src="<%= asset_path 'thumb_up.png' %>" alt="+1" >
          <img id="thumb_down" class="icon" src="<%= asset_path 'thumb_down.png' %>" alt="-1">
        </div>
      <div class="wrapper">
          <label class="subTitle">Location: </label>
          <label id="location" class="text"></label>
        </div>
      <br>
        <div class="buttons">
          <% if user_signed_in? %>
          <a id="newIdeaLink" class="" href="/idea_nodes/new/<%= @root.id %>">
            <div class='btn'>New Idea</div>
          </a>
          <% end %>
          <div class='btn' onclick="return hideInfo();">Close</div>
        </div>
        <br>
    </div>
    <div id="content">
      <div id="MindMapDiv">
          <%= getNodes(@root) %>
        </div>
    </div>
=======
	<%= javascript_include_tag "mindmap"%>
	<%= javascript_include_tag "raphael-min"%>
	<%= javascript_include_tag "js-mindmap"%>
<% end %>
		<div id="popup">
			<h2 id="title" class="text"></h2>
				<div class="wrapper">
					<label>Description: </label></br>
					<label id="desc" class="text"></label>
				</div>
			</br>
				<div class="wrapper">
					<label>Author: </label></br>
					<label id="username" class="text"></label>
				</div>
				</br>
				<div class="wrapper">
					<label>Created At: </label>
					<label id="created_at" class="text"></label>
				</div>
				</br>
				<div class="wrapper">
					<label>Rating: </label>
					<label id="rating" class="text"></label><img id="thumb_up" class="icon" src="<%= asset_path 'thumb_up.png' %>"><img id="thumb_down" class="icon" src="<%= asset_path 'thumb_down.png' %>">
				</div>
			</br>
			</br>
				<div class="buttons">
					<% if user_signed_in? %>
					<a id="newIdeaLink" class="text" href="/idea_nodes/new/<%= @root.id %>"><div class='dark button'>New Idea</div></a>
					<% end %>
					<div class='dark button' onclick="return hideInfo();">Close</div>
				</div>
		</div>
		<header>Mindmap</header>
		<div id="content">
			<div id="MindMapDiv">
			  	<%= getNodes(@root) %>
  			</div>
		</div>
		
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882

app/views/mindmap/search.html.erb
<% content_for :style do %>
  <%= stylesheet_link_tag "search" %>
<% end %>
<% content_for :script do%>
	<%= javascript_include_tag "search" %>
<% end %>
<<<<<<< HEAD
			<div id="search">
				<input id="searchBar" type="text">
				<div onclick="return search('<%= params[:tag] %>');" id="searchButton" class="btn">Search</div>
			<br/>
			<input id="tag" type="hidden" value="<%= @tag %>">
			<div id="sortWraper" class="dark">
=======
		<header>Search</header>
			<div id="search">
				<input id="searchBar" type="text"><div onclick="return search('<%= params[:tag] %>');" id="searchButton" class="dark">Search</div>
			</br>
			<input id="tag" type="hidden" value="<%= @tag %>">
			<div class="dark sort">
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
				<label>Sort By: </label>
				<select id="sort">
					<option>None</option>
					<option>Newest</option>
					<option>Oldest</option>
					<option>User</option>
					<option>Rating</option>
				</select>
			</div>
			</div>
		<div id='content'>
<<<<<<< HEAD
			<input id="pageName" type="hidden" value="discover">
			<% @ideas.each do |node| %>
			<a href="/mindmap/<%= node.id %>">
				<div class="idea">
					<div class="title"><h4><%= node.title %></h4></div>
=======
			<% @ideas.each do |node| %>
			<a href="/mindmap/<%= node.id %>">
				<div class="idea">
					<div class="title"><%= node.title %></div>
>>>>>>> 0852a360a9903c058cf3a12e99f77c7bd48c0882
					<div class="description"><%= node.description %></div>
					<div class="rating"><%= node.rating %></div>
					<div class="username"><%= node.username %></div>
					<div class="createdAt"><%= node.created_at %></div>
				</div> 
			</a>
			<% end %>
		</div>